markdown: redcarpet
pygments: true
paginate: 8

safe:  false
permalink: /:title.html

#Site config
title: 水风的博客 -技术永远是一种哲学和艺术
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: http://shinepengwei.github.io/
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 痕迹
    url: /myProject.html
  - text: 标签
    url: /tags.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html


#Author config
author:
    name: 水风
    email: shinepengwei@163.com
    imageLink: http://tp2.sinaimg.cn/1832671293/180/40020872447/1
    simpleIntro: 水风，南农、东南毕业，目前主要方向为游戏研发。
    detailIntro:
        <li>东南大学-硕士</li>
        <li>南京农业大学-本科</li>
        <li>网易游戏（待毕业入职）</li>
        <li>IT人</li>
        <li>互联网</li>
        <li><a href="http://www.njcoding.com">水风网络</a></li>
        <p>技术永远是一种哲学和艺术。</p>
        <p>兴趣广泛，强烈喜欢网络游戏，并从事游戏研发。</p>
        <p>	对互联网相关的技术、运营、意识形态有着浓厚兴趣。</p>
        <p>技术兴趣广泛，技术能力一般，光而不深，或许因为学习能力不错，目前还没拉下。</p>
        <p>爱阅读，但不仅限于技术，更喜欢阅读一些社会科学、人文方面的书籍。</p>
        <p>伪极客，七分书呆子，二分二流子，一分痛苦的哲学家</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/shinepengwei
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 掌心
      url: http://www.zhanxin.info
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: codingart